# 项目相关配置
ruoyi:
  # 名称
  name: LeBang
  # 版本
  version: 4.0.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  #profile: D:/bajiao/uploadPath
  profile: /home/lebang/file
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为808091
  port: 8091
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
 
# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  100MB
       # 设置总上传的文件大小
       max-request-size:  200MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  main:
    sources:

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi.project.**.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen: 
  # 作者
  author:
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.ruoyi.project.lb
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: lb_

wx:
  qy:
    corpid: ww2873e95a9b5f326c
    agentid: 1000004
    corpsecret: ET2hICW6D5VNw2YnODqR6uy2Rb0piIi1FITuPs2uV0Q
    url:
      access_token: https://qyapi.weixin.qq.com/cgi-bin/gettoken
      login: https://qyapi.weixin.qq.com/cgi-bin/miniprogram/jscode2session
      read_user: https://qyapi.weixin.qq.com/cgi-bin/user/get
      user_sensitivity_information: https://qyapi.weixin.qq.com/cgi-bin/service/getuserdetail3rd?access_token=
      department_information: https://qyapi.weixin.qq.com/cgi-bin/department/list
      department_information_detail: https://qyapi.weixin.qq.com/cgi-bin/user/simplelist
      user_by_code: https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo
  app_client:
    appid: wx6597547107ae5139
    secretid: 14fe1165bc60de3aa6ced71ba8dba2ee
    url:
      code2Session: https://api.weixin.qq.com/sns/jscode2session
      getAccessToken: https://api.weixin.qq.com/cgi-bin/token
      sendMsg: https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send?access_token=
  wx_gzh:
    appid: 111
    secret: 111

qrcode:
  width: 366
  heigth: 366
  url: http://lebang-h5.bajiaostar.com/#/pages/register/register?inviteCode=
sms:
  qcloud:
    appid: 1400268970
    appkey: 855de16d5d1cb6823701f76a20216b41
    templateId: 448202
    smsSign: 贯晶金融